<?php
function get_country_list() {
    $dictionary = [
          1 => ['countryCode' => 'DE', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Germany'],
          2 => ['countryCode' => 'SA', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Saudi Arabia'],
          3 => ['countryCode' => 'AR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Argentina'],
          4 => ['countryCode' => 'AW', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Aruba'], #No existe en city selector
          5 => ['countryCode' => 'AU', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Australia'],
          6 => ['countryCode' => 'AT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Austria'],
          7 => ['countryCode' => 'BE', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Belgium'],
          8 => ['countryCode' => 'BO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Bolivia'],
          9 => ['countryCode' => 'BR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Brazil'],
         10 => ['countryCode' => 'CA', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Canada'],
         11 => ['countryCode' => 'CL', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Chile'],
         12 => ['countryCode' => 'CN', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'China'],
         13 => ['countryCode' => 'CO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Colombia'],
         14 => ['countryCode' => 'KR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'South Korea'],
         15 => ['countryCode' => 'CR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Costa Rica'],
         16 => ['countryCode' => 'CU', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Cuba'],
         17 => ['countryCode' => 'CW', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Curaçao'], #No existe en city selector
         18 => ['countryCode' => 'DK', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Denmark'],
         19 => ['countryCode' => 'EC', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Ecuador'],
         20 => ['countryCode' => 'US', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'United States'],
         21 => ['countryCode' => 'EG', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Egypt'],
         22 => ['countryCode' => 'SV', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'El Salvador'],
         23 => ['countryCode' => 'GB', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'United Kingdom'],
         24 => ['countryCode' => 'SI', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Slovenia'],
         25 => ['countryCode' => 'ES', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Spain'],
         26 => ['countryCode' => 'PH', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Philippines'],
         27 => ['countryCode' => 'FI', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Finland'],
         28 => ['countryCode' => 'FR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'France'],
         29 => ['countryCode' => 'GT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Guatemala'],
         30 => ['countryCode' => 'NL', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Netherlands'],
         31 => ['countryCode' => 'HN', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Honduras'],
         32 => ['countryCode' => 'HK', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Hong Kong S.A.R.'],
         33 => ['countryCode' => 'HU', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Hungary'],
         34 => ['countryCode' => 'IS', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Iceland'],
         35 => ['countryCode' => 'IN', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'India'],
         36 => ['countryCode' => 'ID', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Indonesia'],
         37 => ['countryCode' => 'UK', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'United Kingdom'],
         38 => ['countryCode' => 'IR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Iran'],
         39 => ['countryCode' => 'IE', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Ireland'],
         40 => ['countryCode' => 'IL', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Israel'],
         41 => ['countryCode' => 'IT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Italy'],
         42 => ['countryCode' => 'JP', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Japan'],
         44 => ['countryCode' => 'KR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'South Korea'],
         45 => ['countryCode' => 'LU', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Luxembourg'],
         46 => ['countryCode' => 'MX', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Mexico'],
         47 => ['countryCode' => 'MC', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Monaco'], #No existe en city selector
         48 => ['countryCode' => 'NI', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Nicaragua'],
         49 => ['countryCode' => 'NO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Norway'],
         50 => ['countryCode' => 'PK', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Pakistan'],
         51 => ['countryCode' => 'PA', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Panama'],
         52 => ['countryCode' => 'PY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Paraguay'],
         53 => ['countryCode' => 'PE', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Peru'],
         54 => ['countryCode' => 'PT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Portugal'],
         55 => ['countryCode' => 'PR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Puerto Rico'], #No existe en city selector
         56 => ['countryCode' => 'QA', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Qatar'],
         57 => ['countryCode' => 'GB', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'United Kingdom'],
         58 => ['countryCode' => 'CZ', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Czech Republic'],
         59 => ['countryCode' => 'DO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Dominican Republic'],
         60 => ['countryCode' => 'RO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Romania'],
         61 => ['countryCode' => 'RO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Romania'],
         62 => ['countryCode' => 'RU', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Russia'],
         63 => ['countryCode' => 'SG', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Singapore'],
         64 => ['countryCode' => 'SG', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Singapore'],
         65 => ['countryCode' => 'ZA', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'South Africa'],
         66 => ['countryCode' => 'SE', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Sweden'],
         67 => ['countryCode' => 'CH', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Switzerland'],
         68 => ['countryCode' => 'CH', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Switzerland'],
         69 => ['countryCode' => 'TW', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Taiwan'],
         70 => ['countryCode' => 'TT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Trinidad And Tobago'],
         71 => ['countryCode' => 'TT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Trinidad And Tobago'],
         72 => ['countryCode' => 'TR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Turkey'],
         73 => ['countryCode' => 'UY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Uruguay'],
         74 => ['countryCode' => 'VE', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Venezuela'],
         77 => ['countryCode' => 'AE', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'United Arab Emirates'],
         78 => ['countryCode' => 'PL', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Poland'],
         79 => ['countryCode' => 'IS', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Iceland'],
         80 => ['countryCode' => 'MY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Malaysia'],
         81 => ['countryCode' => 'MY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Malaysia'],
         82 => ['countryCode' => 'MY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Malaysia'],
         83 => ['countryCode' => 'MY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Malaysia'],
         84 => ['countryCode' => 'MY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Malaysia'],
         85 => ['countryCode' => 'MY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Malaysia'],
         86 => ['countryCode' => 'IS', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Iceland'],
         87 => ['countryCode' => 'SY', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Syria'],
         88 => ['countryCode' => 'GR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Greece'],
         89 => ['countryCode' => 'CZ', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Czech Republic'],
         90 => ['countryCode' => 'UA', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Ukraine'],
         91 => ['countryCode' => 'RU', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Russia'],
         92 => ['countryCode' => 'MA', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Morocco'],
         93 => ['countryCode' => 'NZ', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'New Zealand'],
         94 => ['countryCode' => 'BG', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Bulgaria'],
         95 => ['countryCode' => 'JM', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Jamaica'],
         96 => ['countryCode' => 'HT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Haiti'],
         97 => ['countryCode' => 'BO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Bolivia'],
         98 => ['countryCode' => 'HR', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Croatia'],
         99 => ['countryCode' => 'MT', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Malta'],
        100 => ['countryCode' => 'RS', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Serbia'],
        101 => ['countryCode' => 'SK', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Slovakia'],
        102 => ['countryCode' => 'GB', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'United Kingdom'],
        103 => ['countryCode' => 'AO', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Angola'],
        104 => ['countryCode' => 'BH', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Bahrain'],
        105 => ['countryCode' => 'CI', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => "Cote D'Ivoire (Ivory Coast)"],
        106 => ['countryCode' => 'LB', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Lebanon'],
        107 => ['countryCode' => 'VN', 'stateCode' => 'n/a', 'cityName' => 'n/a', 'stateName' => 'n/a', 'countryName' => 'Vietnam'],
    ];
    return $dictionary;
}